### ISSUE TITLE
Will this work with the new ADT Command system 

### ISSUE THREAD

**Issue by mikesalz** [mkormendy/homebridge-node-alarm-dot-com#13]
The new ADT Command system uses alarm.com as its back end.  Is it safe to say that this plugin would therefore work with this system?

**Comment by mkormendy** [comment]
It's possible, but I'm not sure if you have direct access to alarm.com's ADT required credentials. Can you log into alarm.com directly instead of going through ADT?

**Comment by mikesalz** [comment]
Thanks for the super quick response!  I don't know yet.  It's being installed later this week.  But truthfully the only reason why I am going with that service is for the Homebridge compatibility.  I'll check into the alarm.com direct login.  If there is no direct login, I suppose this won't work, eh?

**Comment by mkormendy** [comment]
This specific plugin will only work with direct account login access to alarm.com. Third party installer (middlemen) proxy interfaces were never in the scope of this specific plugin project.
You may be able to get direct access if you contact ADT for the alarm.com account - or, better yet, see if you can download the alarm.com app on your mobile phone. If ADT provides credentials for the alarm.com app, then this *should* in theory still work.

**Comment by mikesalz** [comment]
Here's an update, if you (or any other readers) are interested.  With this system, you have a login that works both in the alarm.com app and the ADT app.  The login DOES work with this plugin, so that is fantastic news!  This is a great plugin.  Thanks for your hard work!!

A couple of questions, now that I have it up and running: 
1. What is the default value for pollTimeoutSeconds?  60?
2. Not sure if this is specific to the ADT installation, but there are a number of cryptically named sensors that popped up that don't appear to be anything I care about.  Perhaps some internal sensors?  Is there a way to hide unneeded sensors?  Or perhaps this could be an enhancement to the plugin?

**Comment by mkormendy** [comment]
@mikesalz, great news!

> 1. What is the default value for pollTimeoutSeconds? 60?

Yes, 60 seconds. In the code it is set here: https://github.com/mkormendy/homebridge-node-alarm-dot-com/blob/cc87b7724771fc8be47633952d8ce1ab76c84142/index.js#L7
Be careful to not go too much lower than 30 seconds for fear of being banned or flagged (however this is an unverified warning, I'm just being conservative with 60 seconds here).

> 2. Not sure if this is specific to the ADT installation, but there are a number of cryptically named sensors that popped up that don't appear to be anything I care about. Perhaps some internal sensors? Is there a way to hide unneeded sensors? Or perhaps this could be an enhancement to the plugin?

I'd like what "cryptically named sensors" are popping up in your homebridge log and also in the Home app so I can properly address hiding unwanted sensors in the config settings for anyone that wants to do so.

**Comment by mikesalz** [comment]
The cryptically named devices are in the attached screenshot from the Home app.  All are named 126D57-X (where X is a number 1 through 8).  I did identify 4 of them on the alarm panel, listed under zones. They appear to be tied to the key fob.  Maybe one zone for each button on the key fob?  The others I am unsure of.  But regardless, I suspect they are useless to HomeKit.
![IMG_53DEF5B59D93-1](https://user-images.githubusercontent.com/46855061/56073716-89be8780-5d76-11e9-9516-92b65529c63f.jpeg)

As far as the timeout, do you think it is sage to drop it down to 45 or 30 seconds, or do you recommend keeping 60?

Thanks again for all of your help!

**Comment by mkormendy** [comment]
What do the devices look like in your alarm.com app (or on the website)?

**Comment by mikesalz** [comment]
Good question.  I logged in and looked at my sensors.  There is one "Controller" device labeled 126D57.  I'm not sure what to make of that...

**Comment by mikesalz** [comment]
Just thinking... Would it be difficult to add a parameter that accepts a delimited list of sensors names... Then any sensors that are found by the names in the list could then be omitted from being added to HomeKit.  Thoughts?

**Comment by mkormendy** [comment]
Oh yes,.. I’ve been planning to work on that for some time, even before your post. Just been really busy with commitments to my current job. I myself need to build this feature for my own need to hide a sensor that I don’t want to monitor.

**Comment by mikesalz** [comment]
You mean your real job?  Get your priorities straight, man!!  :) 
I kid, I kid.  I totally understand.  If and when you do get around to it, I'm happy to help test or do anything else that would be helpful.

**Comment by mikesalz** [comment]
Hey @mkormendy - Sorry to bug you about this again.  I received an email from the thread saying it was going to be marked stale.  I don't know if that means it will be removed/archived.  So I figured I'd send you one more email to see if you have had a chance to work on this one yet?  Thanks again!

**Comment by mkormendy** [comment]
If a comment or activity happens .. it removes the stale label. I've set up the bot to do that so it reminds me to put it back up at the top of my priority list.

**Comment by mkormendy** [comment]
I have a bot that re-adds this to the top of my priority list.

**Comment by mkormendy** [comment]
@mikesalz I managed to get some time this weekend to update the project. I've tested it, and so far it works as planned. See the readme for more info on configuring it.

**Comment by mikesalz** [comment]
Thank you @mkormendy!  It took some monkeying around with the cachedAccessories file and a few restores or my entire Homebridge folder, but I finally got it working! :) :) 
Everything seems to be working like a champ now.  I appreciate your help and hard work!
