### ISSUE TITLE
Can’t Arm Away from Home App

### ISSUE THREAD

**Issue by leaky0320** [mkormendy/homebridge-node-alarm-dot-com#14]
Every time I try to arm my Alarm.com panel from the Home app, it does not allow me to arm Away. I can arm Home and arm Night but not Away. When I click on Away, immediately the system status turns to “Not Responding” and then off. 

Per the Alarm.com app, it seems to be sending a Disarm command instead. 

![IMG_1823](https://user-images.githubusercontent.com/52047924/59900991-e28a4c00-93c7-11e9-935c-b60b359254b9.jpeg)

Here is my config:
      {
            "platform": "Alarmdotcom",
            "name": "Security System",
            "username": "XXXXXXX",
            "password": "XXXXXXX",
            "armingModes": {
                "away": {
                    "noEntryDelay": false,
                    "silentArming": false
                },
                "night": {
                    "noEntryDelay": false,
                    "silentArming": false
                },
                "stay": {
                    "noEntryDelay": false,
                    "silentArming": false
                }
            }
        },

And attached is the log from HomeBridge showing the error I get when I try to Arm Away.

![523D0AAE-3FC7-458E-B688-DB88A6A802C3](https://user-images.githubusercontent.com/52047924/59869605-b0de9a00-9361-11e9-876f-9617c3d2ba52.png)

**Homebridge System (please complete the following information):**
 - Hardware: Pi3
 - OS: Rasbian Latest 
 - Node Type/Version: oznu docker image latest

**Comment by mkormendy** [comment]
That's really odd. Can you set your log level to 4 per the Troubleshooting instructions?

Eg.: 0 = NONE, 1 = ERROR, 2 = WARN, 3 = NOTICE, 4 = VERBOSE

Let me see the output of your login, redact anything you feel is sensitive.

**Comment by leaky0320** [comment]
Of course now I try to replicate the bug and it is working correctly. I had to restart my Raspberry Pi but I had tried that before and it didn’t work. Seems it finally did the trick?

**Comment by mkormendy** [comment]
Well, it just sounds like a glitch. I had just upgraded my nodeJS and reinstalled everything, and wasn’t having any of the issues you were having previously before your reboot, so I’m going to close this ticket.
