### ISSUE TITLE
Locks and Garage Door Opener Progress?

### ISSUE THREAD

**Issue by ngori** [mkormendy/homebridge-node-alarm-dot-com#15]
Just curious on the development for Lock and Garage Door Opener support.  I have both on my ADC setup (Schlage door lock and GoControl garage opener).  I believe I have been able to capture the API calls for both but admittedly my programming skills are rusty at best.  If there is anything I could do to aid the development I'd be happy to help,

**Comment by mkormendy** [comment]
As it is, I don’t have the setup to test this so that’s pretty much why this has stagnated.

**Comment by ngori** [comment]
Cool. I'm working on the interface module now.  I'll do a pull request on everything if/when I get it going.
