### ISSUE TITLE
countdown timer arming timer not triggering

### ISSUE THREAD

**Issue by knuckleheadsmiff** [mkormendy/homebridge-node-alarm-dot-com#17]
**Describe the bug**

When I arm away I never see the countdown timer tigger. But I also don't see it from Alarm.coms shortcut implies on the iPhone. Is this working or just a limitation. I've true with the default setting both true and false for noEntryDelay.

Fyi, I am a FrontPoint customer but use your plugin fork.

(fyi, this plugin is great.)

----------------------------------

I now this is not a bug below but.......

Also any reason why I have your the authentication time longer? Is 10 min a magic number? I understand why it is not shorter.

**Comment by knuckleheadsmiff** [comment]
Ok, so I was confused about what no entry delay does. That just controls if the alarm goes off immediately or not when a sensor Trips.

So I guess my question is just a question, is there a way to arm the system and get the arming count down timer.

**Comment by mkormendy** [comment]
Hey there @knuckleheadsmiff, unfortunately there are some limitations of the API for this that I haven't been able to work around in any performant manner.

The old ticket #7 on my repo still hasn't been resolved, HOWEVER, I find it odd that you don't get the countdown timer chime when you arm your system to "Away" with Homekit/Homebridge.

When I arm the system away (see below), I get the repeating count down timer chime.

![Screen Shot 2019-09-13 at 10 08 25 PM](https://user-images.githubusercontent.com/1437667/64902809-e4d10f00-d673-11e9-9ed3-3fddcef78c88.png)

When I arm the system to Home or Night, I don't get the countdown timer, just one chime and that's it, and they also don't enable the motion sensors inside the house either.

With only our use cases to test with, I can only surmise at this time that it's something particular with the alarm keypad panel(s).

**Comment by knuckleheadsmiff** [comment]
Thanks for responding. Turns out it is walking. I seem to have a delay between the system announcing that it is armed and the countdown starting. It’s like a 10-15 second delay and the the 30 second countdown starts.

I’ll close the bug. 

Do you know why I should not make the Auth timeout longer? Even 10 minutes seems short unless they have a timeout on the key that is returned?

The Plugin is great!

-Russ

**Comment by mkormendy** [comment]
To be honest I simply left this intact from jhurlman's plugin for FrontPoint that I ported to my implementation. I've been running this for quite some time now and I haven't had any problems with it checking in every 10 minutes.
