### ISSUE TITLE
Cannot install the plugin - "not in the NPM registry"

### ISSUE THREAD

**Issue by fenway062213** [mkormendy/homebridge-node-alarm-dot-com#2]
Getting the following error message when I try to  install the plugin. Any help would be appreciated...

> >

 npm ERR! Darwin 17.7.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-alarm-dot-com"
> npm ERR! node v6.11.4
> npm ERR! npm  v3.10.10
> npm ERR! code E404
> 
> npm ERR! 404 Not found : homebridge-alarm-dot-com
> npm ERR! 404 
> npm ERR! 404  'homebridge-alarm-dot-com' is not in the npm registry.
> npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
> npm ERR! 404 
> npm ERR! 404 Note that you can also install from a
> npm ERR! 404 tarball, folder, http url, or git url.
> 
> npm ERR! Please include the following file with any support request:

>

**Comment by mkormendy** [comment]
I'm thinking you'll need to upgrade node (v10+) and npm (v6+). There's plenty of tutorials online on how to do that for your specific operating system.

**Comment by fenway062213** [comment]
@mkormendy actually I figured out what the issue was - I was copying the install command from your readme which is npm install -g homebridge-alarm-dot-com. I didn’t notice that the actual plugin title is Homebridge-node-alarm-dot-com. 

Once I realized that I was able to enter the correct install command in terminal (npm install -g Homebridge-node-alarm-dot-com) and everything was great from there. 

I’m up and running and it is fantastic being able to set my arm modes from the Home app!

**Comment by mkormendy** [comment]
@fenway062213 - Apologies! I've been looking at the code and name for the past 24 hours that I've glossed over the install command completely.

Rest assured, I've corrected the readme and published the change. Thank you for your help with that!
