### ISSUE TITLE
New to Homebridge, attempting to setup alarm.com plugin

### ISSUE THREAD

**Issue by oXb3** [mkormendy/homebridge-node-alarm-dot-com#21]
Hello,

I am hoping that I am putting this in the right place, I do apologize, if I am not. I am trying to figure out how to configure the alarm.com plugin into my config.json file, I am a little confused with the directions, and I am hoping I can get some clarification on it. The "authTimeoutMinutes" and "pollTimeoutSeconds" are not showing in the configuration so I am not sure where those should go in the .json file. Thank you for your time, I am completely new at this and just trying to get my footing here.

Thanks,

Ox

**Comment by mkormendy** [comment]
What does your config file look like? Redact anything sensitive.

**Comment by oXb3** [comment]
Here is my config file the way it is setup currently. I have installed the alarm.com plugin but have yet to add it to my config file...since I am not sure where to put everything.

{
    "bridge": {
        "name": "HOOBS",
        "username": "xxxxxx",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "This file is used for plugin configuration.",
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "amber",
            "sudo": true,
            "standalone": true,
            "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
            "temp": "/sys/class/thermal/thermal_zone0/temp",
            "log": {
                "method": "custom",
                "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x"
            },
            "platform": "config"
        },
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                "username": "xxxxx",
                "password": "xxxxx",
                "countryCode": "1",
                "platform": "tuya",
                "pollingInterval": 10
            }
        }
    ]
}

**Comment by mkormendy** [comment]
@oXb3 this question is really not an issue of the plugin, and more a general issue of the basics of configuring homebridge. That being said, I've taken your config file, cleaned it up a bit, and inserted the alarm.com configuration portion for this alarm.com plugin:

    {
        "accessories": [],
        "bridge": {
            "name": "HOOBS",
            "pin": "031-45-154",
            "port": 51826,
            "username": "xxxxxx"
        },
        "description": "This file is used for plugin configuration.",
        "platforms": [
            {
                
                "platform": "config",
                "name": "Config",
                "auth": "form",
                "log": {
                    "command": "sudo -n journalctl -o cat -n 500 -f -u homebridge -u homebridge-config-ui-x",
                    "method": "custom"
                },
                "port": 8080,
                "restart": "sudo -n systemctl restart homebridge homebridge-config-ui-x",
                "standalone": true,
                "sudo": true,
                "temp": "/sys/class/thermal/thermal_zone0/temp",
                "theme": "amber"
            },
            {
                "platform": "TuyaWebPlatform",
                "name": "TuyaWebPlatform",
                "options": {
                    "countryCode": "1",
                    "password": "xxxxx",
                    "platform": "tuya",
                    "pollingInterval": 10,
                    "username": "xxxxx"
                }
            },
            {
                "platform": "Alarmdotcom",
                "name": "Security System",
                "username": "<ENTER YOUR ALARM.COM USERNAME>",
                "password": "<ENTER YOUR ALARM.COM PASSWORD>"
            }
        ]
    }

I am closing this ticket as it's out of scope for this project. This plugin's prerequisites are having preliminary knowledge and prior homebridge configuration research/education/experience.

I recommend checking out the following links prior to installing any more homebridge plugins:

https://github.com/nfarina/homebridge/blob/master/config-sample.json

https://www.reddit.com/r/homebridge/comments/aml8f9/so_youre_having_trouble_with_your_configjson_file/

https://www.imore.com/how-connect-non-homekit-devices-homekit-using-homebridge
