### ISSUE TITLE
Accessory Status Not Updating/Working

### ISSUE THREAD

**Issue by zachgibson** [mkormendy/homebridge-node-alarm-dot-com#24]
I can control all of my accessories, but the status of each accessory is not working for me. I either get a “No Response” status, or my Security Panel will show “Arming…” or “Disarming…” statuses indefinitely. But again the action *is successful*, just the status doesn’t update correctly.

 - Hardware: Mac mini (2018) running MacOS 10.15.1 (19B88)
 - Node Type/Version: node v12.12.0

**Comment by lwpmoon** [comment]
Can you post a log with these events? Also, what cellular technology does your panel use (3G/CDMA or 4G LTE)? I noticed arming status updates were much slower on my (now deprecated) 3G module compared to my new 4G LTE module. I’m curious whether slow cellular connections are causing these possible timeout issues for you?

**Comment by mkormendy** [comment]
This is likely due to the addition of locks and lights as I have noticed this issue as well after a week of testing.

**Comment by zachgibson** [comment]
Yeah downgrading to v1.2.0 works, but I lose lock accessories. @mkormendy I can try and help debug this if that would be helpful.

**Comment by mkormendy** [comment]
Okay. Yes, sorry it appears that there's some further development that needs to take place in both the node-alarm-dot-com package and also possibly this module as well. I am going to close this ticket, as it is a duplicate of issue #23.
