### ISSUE TITLE
Callback function has already been called by someone else

### ISSUE THREAD

**Issue by wesbro** [mkormendy/homebridge-node-alarm-dot-com#27]
I'm unable to to control my lights through homebridge or the home app with the latest 1.4.1 version. Here's what's happening in the log:

[Homebridge] [1/15/2020, 11:12:32 PM] [Security System] Changing light (########-####, false light level null)
[Homebridge] [1/15/2020, 11:12:33 PM] [Security System] Error: Failed to change light state: Error: POST https://www.alarm.com/web/api/devices/lights/XXXXXXXXXXXXXXXX/turnOff failed: 403
[Homebridge] at fetch.then.then.catch.err (/home/hoobs/.hoobs/node_modules/node-alarm-dot-com/index.js:504:13)
[Homebridge] at process._tickCallback (internal/process/next_tick.js:68:7)
[Homebridge] [1/15/2020, 11:12:33 PM] Unhandled Rejection "Error: This callback function has already been called by someone else; it can only be called one time.".
[Homebridge] [1/15/2020, 11:12:33 PM] Error: This callback function has already been called by someone else; it can only be called one time.
[Homebridge] at /home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/util/once.js:12:13
[Homebridge] at login.then.then.then.then.catch.err (/home/hoobs/.hoobs/node_modules/homebridge-node-alarm-dot-com/index.js:718:9)
[Homebridge] at process._tickCallback (internal/process/next_tick.js:68:7)
[Homebridge] (node:596) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)

**Comment by mkormendy** [comment]
Whats in the XXXXXXXX section?

**Comment by mkormendy** [comment]
@chase9 does this update affect your alarm.com setup with lights?

**Comment by wesbro** [comment]
> Whats in the XXXXXXXX section? It should be something like '94964451-1205'.
> What versions of node and homebridge are you running?

Yes- that's exactly what's in the xxxx section. I swapped it out because I assumed it was specific to my account or something. Running Homebridge 0.4.50 and Node 1.4.1

**Comment by mkormendy** [comment]
Umm .. well my versions are:
Node.js Version: 12.4.0
Homebridge Version: 0.4.50

I'm not sure what comparative version of node.js you have in relation to mine, but that could be the culprit.

**Comment by wesbro** [comment]
So I'm a newbie to all of this and actually run my home bridge setup via a HOOBS box. This is what I see on the plugin installation page.

https://a.cl.ly/6quLJDKe

Does this tell you anything?

I'm guessing I've actually given you a plugin version number, not a node version (which I have no idea where to find)?

**Comment by mkormendy** [comment]
No that's not the version of your node.js that's the version of this plugin. You'd have to log into the "command line" of your hoobs box and run something like:
```
node -v
```

**Comment by wesbro** [comment]
like this? https://a.cl.ly/9ZuNyWDm

**Comment by mkormendy** [comment]
Yeah, you're a couple major semver versions behind with your node - that *could* be an issue.

I'm not sure the best course of updating node on Hoobs, I'd scour their documentation or google that to find out best to.

**Comment by mkormendy** [comment]
Can you also run this at the command line:
```
sudo npm list node-alarm-dot-com
```

**Comment by chase9** [comment]
> @chase9 does this update affect your alarm.com setup with lights?

You've been busy! Just installed the latest and not seeing any issues with lights or locks.

**Comment by BobbySlope** [comment]
In HOOBS you can update node js voa top right menu-> terminal and enter this command

Used to upgrade Node to 12.14.0
`
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node lts `

Be careful if you have other plugin running that not support latest lts you risk to get errors by other plugins. 

To rollback: 
wget -q -O - http://bit.ly/get-hoobs | sudo bash /dev/stdin --node stable 

- Used to downgrade Node to 10.17.0

**Comment by mkormendy** [comment]
@chase9 thanks Chase! Do you have any idea why the others might be having issues like in #23?

@BobbySlope well look at that! How were you capable of being so timely?

**Comment by chase9** [comment]
I'm not, but I can look more into it when I get home. I'm surprised to see this callback issue as I explicitly callback before I'm supposed to to get around Siri's timeout...

The joys of home automation 😅

**Comment by mkormendy** [comment]
@chase9 I may have removed that in my code refactoring. I'm not exactly sure where that part was though .. because I remember you mentioning it during the work you did.

**Comment by BobbySlope** [comment]
Just got the confirmation that the next release of HOOBS will be on node 12

**Comment by mkormendy** [comment]
@BobbySlope how did you come across this plugin and the potential issue with the version of node in hoobs?

**Comment by wesbro** [comment]
My HOOBS box crashed and I just got some assistance to get it back up and running. I restored the plugins and config.

I'm running Homebridge Version	0.4.50 and Node Version	12.14.1


I ran your command and this is what I get:

@hoobs/hoobs@3.1.20 /home/hoobs/.hoobs
└─┬ homebridge-node-alarm-dot-com@1.4.1
  └── node-alarm-dot-com@1.7.5 
  
  
When I ask alarm dot com to turn off a light, I get the following in terminal (which appears to be the same as before):



[Homebridge] (node:626) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
[Homebridge] [1/18/2020, 12:48:20 PM] [Security System] Changing light (94964451-1205, false light level null)
[Homebridge] [1/18/2020, 12:48:20 PM] [Security System] Error: Failed to change light state: Error: POST https://www.alarm.com/web/api/devices/lights/94964451-1205/turnOff failed: 403
    at /home/hoobs/.hoobs/node_modules/node-alarm-dot-com/index.js:504:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[Homebridge] [1/18/2020, 12:48:20 PM] Unhandled Rejection "Error: This callback function has already been called by someone else; it can only be called one time.".
[Homebridge] [1/18/2020, 12:48:20 PM] Error: This callback function has already been called by someone else; it can only be called one time.
    at /home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/util/once.js:12:13
    at /home/hoobs/.hoobs/node_modules/homebridge-node-alarm-dot-com/index.js:718:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[Homebridge] (node:626) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 4)

**Comment by BobbySlope** [comment]
@wesbro Was running an old version of node on hoobs and he contacted us via support chat

**Comment by mkormendy** [comment]
@chase9 so when you're seeing no issues with the lights/locks, this means that when you attempt to turn off a light .. you don't get the same issue as @wesbro ?

**Comment by wesbro** [comment]
One thing I have noticed is that the accessories are reporting their correct state in Hombridge after a restart. The light I was trying to turn off says its on when I restart the box.

**Comment by wesbro** [comment]
@mkormendy I'd like to go back to a previous version of the plugin. Is there a command I can run in the terminal to do this? And I assume I should uninstall the current version before I do this?

**Comment by mkormendy** [comment]
Check #23 there are instructions in that thread.

**Comment by wesbro** [comment]
I tried rolling back to 1.3.2 and this is what I got: https://a.cl.ly/ApuOlDxx

**Comment by BobbySlope** [comment]
@wesbro Hoobs does not install plugins globally. See here on how to install plugins from terminal in hoobs: https://hoobs.org/knowledge-base/how-plugins-work-with-hoobs-advanced/

**Comment by wesbro** [comment]
@mkormendy I might hold off a few more days and just install your plugin through HOOBS once its fixed. Even the manual method of installation that @BobbySlope suggests is a bit out of my comfort zone. Any thoughts yet one what's causing the current version of the plugin to not work with my home bridge? Just wondering if it might be a setting on my end or if its in the plugin.

**Comment by mkormendy** [comment]
@wesbro I don’t have a roadmap to fix what I can’t reproduce. I do run homebridge as installed globally, so that could be an issue - but beyond that, that’s what this package was setup to run in - homebridge, not a custom setup with hoobs.

**Comment by wesbro** [comment]
HOOBS support showed me how to rollback. I tried a few different versions (I _think_ I was running version 1.3.2 before all this began, but I couldn't get any better results from that or 1.4.0. So I am currently on 1.3.1 -- still nothing. FYI, here's the result of that command to roll back: https://a.cl.ly/7KuyXzoZ

So it would seem to me that something in my updating to 1.4.1 (3 days ago when I originally posted here) broke this? 

By the way, is below a normal behavior for each device as it's initializing the plugin?


[Homebridge] [1/18/2020, 10:28:45 PM] [Security System] Removing Foyer Lamp (94964451-1202) from HomeBridge.
[Homebridge] [1/18/2020, 10:28:45 PM] [Security System] Adding Light "Foyer Lamp" (id=94964451-1202, uuid=896bd3b7-f662-4fbc-8835-5fd8655255ae) (2 2)
[Homebridge] [1/18/2020, 10:28:45 PM] [Security System] Updating light Foyer Lamp (94964451-1202), state=1, prev=2
[Homebridge] [1/18/2020, 10:28:45 PM] [Security System] Added light Foyer Lamp (94964451-1202)

**Comment by wesbro** [comment]
By the way, here's the full log of trying to change one light:

`[Homebridge] [1/18/2020, 10:40:12 PM] [Security System] Changing light (94964451-1205, false light level null)
[Homebridge] [1/18/2020, 10:40:12 PM] [Security System] Error: Failed to change light state: TypeError: method is not a function
    at /home/hoobs/.hoobs/node_modules/homebridge-node-alarm-dot-com/index.js:797:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[Homebridge] [1/18/2020, 10:40:12 PM] Unhandled Rejection "Error: This callback function has already been called by someone else; it can only be called one time.".
[Homebridge] [1/18/2020, 10:40:12 PM] Error: This callback function has already been called by someone else; it can only be called one time.
    at /home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/util/once.js:12:13
    at /home/hoobs/.hoobs/node_modules/homebridge-node-alarm-dot-com/index.js:806:9
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[Homebridge] (node:1922) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 3)
[Homebridge] [1/18/2020, 10:40:13 PM] [Security System] Warning: Sensor with unknown state 0`

**Comment by wesbro** [comment]
I just realized this isn't happening with locks. This is only happening with lights. Here's a successful locking...

[Homebridge] [1/19/2020, 8:16:23 AM] [Security System] (un)secureLock)(94964451-1203, 1)
[Homebridge] [1/19/2020, 8:16:31 AM] [Security System] Updating lock Front Door (94964451-1203), state=1, prev=0

**Comment by wesbro** [comment]
@mkormendy One thing I'm not entirely clear on is what the difference is between these 2 plugins that show up in the HOOBS interface: https://a.cl.ly/ApuOlP05

The first one goes here: https://github.com/mkormendy/homebridge-node-alarm-dot-com#readme

The second one goes here: https://github.com/mkormendy/node-alarm-dot-com#readme


Are those essentially the same thing @BobbySlope ?

**Comment by mkormendy** [comment]
@wesbro homebridge-node-alarm-dot-com relies on node-alarm-dot-com. However, they should not be installed separately at the same level.

All you need to install is homebridge-node-alarm-dot-com. The sub-package node-alarm-com will be automatically installed within the folders of homebridge-node-alarm-com.

Homebridge-node-alarm-dot-com is a wrapper application that works with homebridge and operates the core node-alarm-dot-com interface.

**Comment by wesbro** [comment]
@mkormendy cool - thanks.

**Comment by wesbro** [comment]
As has been well established here, I really have no idea what I'm doing. I can do a bunch of trial/error and terminal copy/paste -- but that's about it. And I've done a lot in the past few days. I'm starting to think this issue might have less to do with the plugin or homebridge -- and something to do with the alarm.com service. Currently, the only plugin I really care about running on Homebridge is the alarm-dot-com plugin. So I'm completely fine wiping my homedbrige box (a HOOBS box in this case) as it doesn't really disrupt anything else I want to run. Here's a summary of what I've tried most recently.

HOOBS walked me through how to completely flash the box back to factory settings, which gave me Homebridge Version 0.4.50 and the latest node (v12). I tried alarm-dot-com plugin version 1.3.2 and 1.4.1, but the issues didn't go away. But since I ultimately wanted to re-create the same conditions as when I received the box, I reflashed the SD card in the box with an older version  which gave me the old node (10.17.0). I then tried various versions of the alarm-dot-com plugin (1.3.2, 1.4.0, 1.4.1) and still no luck. Throughout various plugin versions and homebridge node versions I did loose functionality with the locks, but currently the locks are working.

I have no idea what "this callback function has already been called by someone else" actually means, but it sounds like it's getting duplicate requests. I don't know if that duplicate request is at the homebridge or alarm.com level. I also don't know how my own alarm.com setup affects any of this. If it helps I can post the details of my alarm.com panel and devices here.

_I went ahead and just updated everything to the most recent versions, so I currently have:_

- HOOBS 3.1.20
- Homebridge 0.4.50
- Node 10.17.0
- Alarm Dot Com 1.4.1

I'm happy to help with any further testing, even if that means completely wiping my box, etc. Just let me know -- I'd love to get this back up and running! Thankss!

**Comment by wesbro** [comment]
@mkormendy Have you been able to replicate the issue? Do you know yet if it's an issue with the plugin or the alarm.com service? Thanks for all your work on this!

**Comment by mkormendy** [comment]
I have not. I’ve been pulled away with a new bunch of projects at work and haven’t even had time to look at any of the issues.

**Comment by wesbro** [comment]
@mkormendy ok. By the way, do you know what version was active on Jan 14? We’re going to try rolling back to that one.

**Comment by mkormendy** [comment]
@wesbro referring to https://github.com/mkormendy/homebridge-node-alarm-dot-com/issues/29#issuecomment-590460094 can you paste here what the error log looks like?

**Comment by wesbro** [comment]
@mkormendy 

![Image 2020-02-24 at 3 01 39 PM](https://user-images.githubusercontent.com/29920429/75186806-b1140e00-5716-11ea-8c33-eaf66d139654.png)

**Comment by wesbro** [comment]
@BobbySlope identified the code a few weeks ago that was causing issues.

**Comment by mkormendy** [comment]
Can you test something for me? With the new index file, go to line 665, you should see this block of code:

```
    this.login()
      .then(res => method(id, brightness, res)) // Usually 20-30 seconds
      .then(res => res.data)
      .then(light => {
        this.setLightState(accessory, light)
      })
      .then(callback())
      .catch(err => {
        this.log(`Error: Failed to change light state: ${err.stack}`)
        this.refreshDevices()
        callback(err)
      })
```

Change it to this:

```
    this.login()
      .then(res => method(id, brightness, res)) // Usually 20-30 seconds
      .then(res => res.data)
      .then(light => {
        this.setLightState(accessory, light)
      })
      .then(_ => callback())
      .catch(err => {
        this.log(`Error: Failed to change light state: ${err.stack}`)
        this.refreshDevices()
        callback(err)
      })
```

Restart homebridge and attempt to control the light and monitor the logs. Let me know if the error persists.

**Comment by wesbro** [comment]
@mkormendy Still not working. Here's the log. 
![Image 2020-02-24 at 3 37 54 PM](https://user-images.githubusercontent.com/29920429/75189377-07378000-571c-11ea-8db6-4d339256e36e.png)

Also, here's my index file, so you can check to make sure I didn't screw something up.

[Index.txt](https://github.com/mkormendy/homebridge-node-alarm-dot-com/files/4246775/Index.txt)

**Comment by mkormendy** [comment]
Okay, try this file: 

[Index2.txt](https://github.com/mkormendy/homebridge-node-alarm-dot-com/files/4246871/Index2.txt)

Post your log of any errors again.

**Comment by wesbro** [comment]
@mkormendy lock still works, but not yet on light. Here's the log:

![Image 2020-02-24 at 4 16 53 PM](https://user-images.githubusercontent.com/29920429/75191851-2389eb80-5721-11ea-9fe6-e0b6d0798fc8.png)

**Comment by mkormendy** [comment]
Sorry I just saw this in our thread:

> @mkormendy ok. By the way, do you know what version was active on Jan 14? We’re going to try rolling back to that one.

That would be this: https://github.com/mkormendy/homebridge-node-alarm-dot-com/releases/tag/1.4.0

> @BobbySlope identified the code a few weeks ago that was causing issues.

Where did he identify this?

> @mkormendy lock still works, but not yet on light. Here's the log:

Do you delete the `cachedAccessories` file and restart homebridge every time you attempt with a new index.js file?

**Comment by mkormendy** [comment]
Try this file, there should be a big block of data that outputs to the log, it may be sensitive in nature so feel free to email it to me instead (mike@somethinginteractive.com).

[Index3.txt](https://github.com/mkormendy/homebridge-node-alarm-dot-com/files/4246967/Index3.txt)

**Comment by wesbro** [comment]
> > @BobbySlope identified the code a few weeks ago that was causing issues.
> 
> Where did he identify this?

He told me their developer was going to reach out to you, but here's what he said to me in our conversation: "there's an issue on code line 797"

![85176559_3073814882685066_1637122429497114624_n](https://user-images.githubusercontent.com/29920429/75193044-76fd3900-5723-11ea-8da0-31da00d26a0b.png)

**Comment by wesbro** [comment]
> Do you delete the `cachedAccessories` file and restart homebridge every time you attempt with a new index.js file?

I'm not sure what command to run to delete that file. But yes, I restarted each time.

**Comment by mkormendy** [comment]
> > Do you delete the `cachedAccessories` file and restart homebridge every time you attempt with a new index.js file?
> 
> I'm not sure what command to run to delete that file. But yes, I restarted each time.

Steps to delete or empty the cached accessories are in the pinned issue https://github.com/mkormendy/homebridge-node-alarm-dot-com/issues/28

**Comment by mkormendy** [comment]
> He told me their developer was going to reach out to you, but here's what he said to me in our conversation: "there's an issue on code line 797"

Surely that can't be line 797 in our modified file, since there are code changes .. the line numbers likely aren't relevant any more. But, line 797 in the version that he identified it in is still good, just not sure which version he used. You'll have to ask.

**Comment by wesbro** [comment]
> > He told me their developer was going to reach out to you, but here's what he said to me in our conversation: "there's an issue on code line 797"
> 
> Surely that can't be line 797 in our modified file, since there are code changes .. the line numbers likely aren't relevant any more. But, line 797 in the version that he identified it in is still good, just not sure which version he used. You'll have to ask.

I think we were testing 1.3.1 when he found that

**Comment by mkormendy** [comment]
> I think we were testing 1.3.1 when he found that

Well if that was the case, at that version, the supposed issue would be with the locks and not the lights - but you're issue from the beginning has only been with the lights.

Did you manage to get the big block of data printed out in the log with Index3.txt?

**Comment by wesbro** [comment]
> > I think we were testing 1.3.1 when he found that
> 

I should clarify that we were testing 1.3.1, but the version I have now is 1.4.1 (plus all these modifications to the index file).

just emailed log output

**Comment by drclayton** [comment]
Is there any more info on this error? I seem to be getting the same error for my lights as posted originally ("Error: This callback function has already been called by someone else; it can only be called one time."). If you need any more help to try and track down the issue, I can try to do what I can to help!

**Comment by chase9** [comment]
Sorry about the long absence. Now that I'm locked in the house I suspect I'll have more time to work on projects :) I do still see that error and will take a look at fixing it soon.

**Comment by mkormendy** [comment]
@chase9 I have a link for a Slack channel that I created for this plugin if you want to collaborate interactively...

https://join.slack.com/t/homebridgeala-v4q9013/shared_invite/zt-d5cvrsmq-fWV2OZtmPYVewEhSUu8a0A
