### ISSUE TITLE
panel disappears

### ISSUE THREAD

**Issue by jnanes** [mkormendy/homebridge-node-alarm-dot-com#3]
hey mike! 

Great work here, i wanted to report something I am noticing, and hopefully help track down the cause. It seems at each start of homebridge, the security panel is added/deleted. for example, if I launch homebridge and can control the panel, upon the next restart of homebridge the panel is gone. all my window sensors remain. if i restart again, the panel comes back.

is there anything I can provide to help track this down? I did rename the cachedaccessories folder before the initial launch of homebridge with your plugin installed.

**Comment by mkormendy** [comment]
Quick question, how are you launching homebridge? Is it run as a service daemon?

**Comment by jnanes** [comment]
it was, however, I switched to launching homebridge via pm2, and it appears to be resolved.

**Comment by mkormendy** [comment]
Okay thanks for following up. Without a way to reproduce the problem, I cannot troubleshoot and provide a fix for the issue that was occurring on your system.

**Comment by jnanes** [comment]
agreed! I prefer pm2 anyway!
