### ISSUE TITLE
GET null failed:  The "url" argument must be of type string

### ISSUE THREAD

**Issue by ansuz07** [mkormendy/homebridge-node-alarm-dot-com#32]
Just started getting a new error this morning.  No changes to the config or the base machine

     [3/16/2020, 12:50:01 PM] [Security System] Error: GET null failed: GET null failed: The "url" argument must be of type string. Received type object
     at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:114:17
     at processTicksAndRejections (internal/process/task_queues.js:93:5)

Any ideas?

**Comment by rivertonrock** [comment]
I came here to report the same Issue, and it looks like @ansuz07 beat me to it. Here is the error I am receiving:

> [3/16/2020, 8:19:43 AM] [Security System] Error: GET null failed: GET null failed: The "url" argument must be of type string. Received type object
>     at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:114:17
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by estevanb** [comment]
Same thing here with me:

UNHANDLED ERROR: Error: GET null failed: GET null failed: The "url" argument must be of type string. Received null
    at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:114:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by ngori** [comment]
I'm not experiencing this error this morning but I'm running my own
non-public fork with garage door support.  Just looking at the
nod-alarm-dot.com/index.js it appears there is difficulty loading the with
mobile session url login used to capture the session and cookies used
elsewhere.  I'm wondering if everyone has the same alarm.com provider?
Perhaps a mandated change to 2 factor?

**Comment by ansuz07** [comment]
I'm already running it via 2 factor, so that isn't the issue.  

Updating with bug report template:

**Describe the bug**
Can no longer access any functions on Alarm.com

**To Reproduce**
Steps to reproduce the behavior:
1. Install plugin and set up.
2.  On reboot, plugin will throw error.  No functions can be polled or controlled.

**Expected behavior**
Should access the Alarm.com server and show available devices

**Screenshots**
Error Message as follow:

     [3/16/2020, 12:50:01 PM] [Security System] Error: GET null failed: GET null failed: The "url" argument must be of type string. Received type object
     at /usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:114:17
     at processTicksAndRejections (internal/process/task_queues.js:93:5)


**Homebridge System (please complete the following information):**
 - Hardware: LXC Container
 - OS: Ubuntu Bionic Beaver (18.04.4 LTS) 
 - Node Type/Version: v12.16.1 

**Additional context**
None

**Comment by estevanb** [comment]
My front end is Brinks Security and it does not have two factor authentication

**Comment by kaganae** [comment]
Same issue, also with no changes to my config.

Mar 16 22:33:43 raspberrypi homebridge[2832]: [2020-3-16 22:33:43] [Security System] Logging into Alarm.com as XXXXX@gmail.com
Mar 16 22:33:43 raspberrypi homebridge[2832]: [2020-3-16 22:33:43] [Security System] Error: GET null failed: GET null failed: Parameter "url" must be a string, not object
Mar 16 22:33:43 raspberrypi homebridge[2832]:     at get.then.catch.err (/usr/lib/node_modules/homebridge-node-alarm-dot-com/node_modules/node-alarm-dot-com/index.js:114:17)
Mar 16 22:33:43 raspberrypi homebridge[2832]:     at <anonymous>
Mar 16 22:33:43 raspberrypi homebridge[2832]:     at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by dshenson** [comment]
Same issue for me.  Looks like brinks updated their alarm.com interface

**Comment by drclayton** [comment]
I am getting this error as well, but not using Brinks.

**Comment by ngori** [comment]
I'm also now getting this error. It's in the same spot in my fork related
to capturing the session URL from the mobile page.   Looks like something
server side was changed across all ADC providers.

**Comment by mkormendy** [comment]
Hello all,

Yes I am getting these errors and cannot operate my alarm system now either.
Something has changed in the payload received back from ADC and I need to analyze the payload and see how to work around it (if possible).

NOTE: my employer is in full coronavirus lockdown, and I've been busy with some fast-turnaround initiatives with regard to the pandemic with our company. I'll try to fit in some time to look at this as this seems like it's affecting everyone now.

**Comment by ulo-swe** [comment]
I am also getting the exact sam error.

**Comment by G8toe** [comment]
I am also getting this error, ADT provider, no 2FA enabled.

**Comment by ngori** [comment]
@mkormendy 

It looks like ADC changed the URL redirect scheme in use.   node-alarm-com uses "https://www.alarm.com/pda/Default.aspx' and that URL no longer has a Location header that was being used.   I'm trying to see if I can rewrite it to get it working again.  If I can sort it out on my private fork I'll let Mike know.

> Hello all,
> 
> Yes I am getting these errors and cannot operate my alarm system now either.
> Something has changed in the payload received back from ADC and I need to analyze the payload and see how to work around it (if possible).
> 
> NOTE: my employer is in full coronavirus lockdown, and I've been busy with some fast-turnaround initiatives with regard to the pandemic with our company. I'll try to fit in some time to look at this as this seems like it's affecting everyone now.

**Comment by mkormendy** [comment]
> It looks like ADC changed the URL redirect scheme in use. node-alarm-com uses "https://www.alarm.com/pda/Default.aspx' and that URL no longer has a Location header that was being used. I'm trying to see if I can rewrite it to get it working again. If I can sort it out on my private fork I'll let Mike know.

So, it's been a long time since I've looked at the process for this and I have no idea what the general value for Location was set in the response header. Since it's not being provided any more, I'm at a loss as to what I can put in place with that. Back to fumbling in the dark until we find that.

**Comment by ansuz07** [comment]
It looks like this issue effects _everything_ that touches Alarm.com right now.

I don't know if it is helpful, but there is some work going on here too:

https://github.com/Xorso/pyalarmdotcom/pull/13

**Comment by mkormendy** [comment]
@ansuz07 thanks for that. I've had a little success with initiating a new login process, however still having errors with the correct session procedures.

**Comment by sdlevi27** [comment]
+1 for this issue.  Local dealer provider, no 2FA enabled.

**Comment by ansuz07** [comment]
I did some research yesterday and it looks like this is affecting everyone who uses a 3rd party integration based on the pda login workflow. 

I think the best course of action is just to let folks work through it.

**Comment by mkormendy** [comment]
I'm going to lock the conversation to avoid additional 1+ type comments. This issue is verified as a valid problem and widespread with efforts to fix it, in progress.

**Comment by ngori** [comment]
I got it back working with the help of an actual web developer friend tonight.  Short version is we updated the loginObj for the new form fields.  Removed all the references to the mobile login to avoid the redirect issues and pointed to the standard login URL.  I'm getting the occasional ECONNRESET when I restart homebridge but I think I'm bumping into some server side limiting not necessarily a problem with the code itself.  The code is ugly and also has my garage door implementation but obviously we need a pull request to get it out and tested.

**Comment by mkormendy** [comment]
@ngori, independently I also got it working as well and have cleaned up the code and removed extra crap that is no longer necessary. Also made things more semantic in the concept of how the login process works. I'll be publishing an update shortly, just doing some final testing.

**Comment by mkormendy** [comment]
I believe I've fixed the login issue. I'm going to discard your pull-request @ngori in favor of my cleaned up version.

**Note:** I see some lag in the updating of the status of the home.app on my Iphone for the alarm, but I haven't restarted my homekit hub to see if that will fix it.

**Comment by DMBlakeley** [comment]
Special thanks to you and team for addressing the alarm.com changes in a timely manner! Much appreciated!

**Comment by estevanb** [comment]
Amazing job! Everything working smooth now!!!!!

**Comment by ulo-swe** [comment]
Works great for me also. Thank you so very much.
