### ISSUE TITLE
IgnoredDevices (to hide motion sensor from Homekit) not working

### ISSUE THREAD

**Issue by wmlorenzo** [mkormendy/homebridge-node-alarm-dot-com#41]
I used the following code to hide a Motion sensor (similar to the sample code where “96922426-1” is replaced with the ID of the motion sensor that I found in my logs)

    "ignoredDevices": [
        "96922426-1",
    ]

However I can still see it in Homekit. Is there any other way I can hide a sensor?

I have tried restarting the HOOBS homebridge service and also rebooting the HOOBS device with no success.

I also tried replacing the ID of the Motion sensor with a Contact sensor to see if there was just an issue with the motion sensors however it still didn’t work. There seems to be an overall issue hiding sensors for my instance.

Otherwise, everything is working fine e.g. the sensors accurately show as open or closed, I can arm/disarm the alarm from homekit, etc.

Thanks

**Comment by wmlorenzo** [comment]
I see the following in the pinned issue: 

_Refresh the accessories cache by starting Homebridge with the -R flag:
homebridge -R
If your homebridge is set to start on boot, you may need to disable that first and start it manually on the command line to refresh the cache and see if the problems continue while in this setup before restoring the start on boot setup._

So I stopped the homebridge service on my HOOBS device. Then I went to the terminal prompt from within the HOOBS GUI and typed in the “homebridge - R” command without the quotes. It said “bash: homebridge: command not found”

If you have more instructions for a HOOBS user like myself that’d be great. if not no worries and this can be closed. I can deal with it if needed.

Thanks

**Comment by mkormendy** [comment]
I'm not sure how hoobs has their setup. But you can also follow the instructions at the bottom of this repo's main README.md.
