### ISSUE TITLE
ReferenceError: lock is not defined

### ISSUE THREAD

**Issue by wjlester** [mkormendy/homebridge-node-alarm-dot-com#46]
**Describe the bug**

Logs regularly indicate display (every 60 seconds) "[Security System] ReferenceError: lock is not defined".

**To Reproduce**

Normal operation (continuous, persistent through restarts and after clearing the cachedAccessories)
**Expected behavior**

**Screenshots**

`[Security System] ReferenceError: lock is not defined
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/index.js:293:38
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/index.js:290:27
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-node-alarm-dot-com/index.js:261:22
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**ADC-SystemStates.json**

`"locks": [
      {
        "id": "********-1255",
        "type": "devices/lock",
        "attributes": {
          "state": 2,
          "desiredState": 2,
          "maxUserCodeLength": 4,
          "supportsScheduledUserCodes": false,
          "supportsTemporaryUserCodes": false,
          "supportsLatchControl": false,
          "canBeSaved": true,
          "canChangeDescription": true,
          "description": "Garage Entry",
          "canConfirmStateChange": true,
          "remoteCommandsEnabled": true,
          "hasPermissionToChangeState": true,
          "deviceIcon": {
            "icon": 181
          },
          "batteryLevelNull": 100,
          "lowBattery": false,
          "criticalBattery": false
        },
        "relationships": {
          "system": {
            "data": {
              "id": "********",
              "type": "systems/system"
            }
          },
          "stateInfo": {
            "data": {
              "id": "********-1255-3",
              "type": "devices/state-info"
            }
          }
        }
      },
      {
        "id": "********-1257",
        "type": "devices/lock",
        "attributes": {
          "state": 1,
          "desiredState": 1,
          "maxUserCodeLength": 8,
          "supportsScheduledUserCodes": true,
          "supportsTemporaryUserCodes": true,
          "supportsLatchControl": false,
          "canBeSaved": true,
          "canChangeDescription": true,
          "description": "Front Door",
          "canConfirmStateChange": true,
          "remoteCommandsEnabled": true,
          "hasPermissionToChangeState": true,
          "deviceIcon": {
            "icon": 182
          },
          "batteryLevelNull": 100,
          "lowBattery": false,
          "criticalBattery": false
        },
        "relationships": {
          "system": {
            "data": {
              "id": "********",
              "type": "systems/system"
            }
          },
          "stateInfo": {
            "data": {
              "id": "********-1257-2",
              "type": "devices/state-info"
            }
          }
        }
      }
    ],
    "relationships": {
      "partitions": {
        "data": [
          {
            "id": "********-127",
            "type": "devices/partition"
          }
        ],
        "meta": {
          "count": "1"
        }
      },
      "locks": {
        "data": [
          {
            "id": "********-1255",
            "type": "devices/lock"
          },
          {
            "id": "********-1257",
            "type": "devices/lock"
          }
        ],
        "meta": {
          "count": "2"
        }
      },`
**Homebridge System (please complete the following information):**
* **Node.js Version**: v12.18.3
* **NPM Version**: v6.14.6
* **Homebridge Version**: Version 1.1.1
* **Operating System**: Raspbian / Ubuntu / Debian / Windows / macOS / **Docker**
* **Process Supervisor**: **Docker** / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Additional context**

THANKS!

**Comment by ngori** [comment]
@mkormendy I noticed this bug and changed it in PR with the garage code. Just the wrong device type in that section of code

**Comment by mkormendy** [comment]
Yup, verified, and saw that in you PR @ngori thanks for catching that. I'll likely be pushing out a new release in the next 24 hours or less.

**Comment by mkormendy** [comment]
A new release is out with the fix.
