### ISSUE TITLE
Issues arming via siri

### ISSUE THREAD

**Issue by jnanes** [mkormendy/homebridge-node-alarm-dot-com#6]
Hey Mike,

When attempting to arm the alarm using siri,I get an error, "Sorry, arming the entrance security panel returned a fault, check the home app for more info"

I can use the home app with no issues.

**Comment by mkormendy** [comment]
Hrmm, what did the Home app say about your security system immediately after the error occurred?

Was the phone unlocked?

**Comment by jnanes** [comment]
when i opened it, there was no error and it let me change the status. the phone was unlocked.

**Comment by mkormendy** [comment]
Does it do this every time you try it, or do you think it was a ‘one-off’ glitch?
The only reason why I’m saying that is that I cannot reproduce the issue.

**Comment by jnanes** [comment]
Very possibly. Tested a few more times and it’s working. Sorry about that I’ll let you know if it returns and try to capture more detail

**Comment by mkormendy** [comment]
Okay, this may have been a connection issue, will reopen or create a new ticket.
